'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class UserMessages1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PSMGlobal.UserMessages1", GetType(UserMessages1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property btn_cancel() As String
            Get
                Return ResourceManager.GetString("btn_cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print.
        '''</summary>
        Friend Shared ReadOnly Property btn_Print() As String
            Get
                Return ResourceManager.GetString("btn_Print", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend Shared ReadOnly Property btn_search() As String
            Get
                Return ResourceManager.GetString("btn_search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Existence.
        '''</summary>
        Friend Shared ReadOnly Property chk_Exit() As String
            Get
                Return ResourceManager.GetString("chk_Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nothing.
        '''</summary>
        Friend Shared ReadOnly Property chk_Noth() As String
            Get
                Return ResourceManager.GetString("chk_Noth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend Shared ReadOnly Property cmd_SEARCH() As String
            Get
                Return ResourceManager.GetString("cmd_SEARCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English name.
        '''</summary>
        Friend Shared ReadOnly Property english() As String
            Get
                Return ResourceManager.GetString("english", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Say greeting.
        '''</summary>
        Friend Shared ReadOnly Property hello() As String
            Get
                Return ResourceManager.GetString("hello", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to By Code.
        '''</summary>
        Friend Shared ReadOnly Property opt_Code() As String
            Get
                Return ResourceManager.GetString("opt_Code", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to By Name.
        '''</summary>
        Friend Shared ReadOnly Property opt_Name() As String
            Get
                Return ResourceManager.GetString("opt_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CUSTOMERS CODE CONTROL.
        '''</summary>
        Friend Shared ReadOnly Property PFP70101() As String
            Get
                Return ResourceManager.GetString("PFP70101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TEST BOM CONTROL.
        '''</summary>
        Friend Shared ReadOnly Property PFP70108() As String
            Get
                Return ResourceManager.GetString("PFP70108", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DYEING PROCESSING BOM CONTROL.
        '''</summary>
        Friend Shared ReadOnly Property PFP70109() As String
            Get
                Return ResourceManager.GetString("PFP70109", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FABRIC CODE CONTROL.
        '''</summary>
        Friend Shared ReadOnly Property PFP70111() As String
            Get
                Return ResourceManager.GetString("PFP70111", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to COLOR CODE CONTROL.
        '''</summary>
        Friend Shared ReadOnly Property PFP70121() As String
            Get
                Return ResourceManager.GetString("PFP70121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to YARN CODE CONTROL.
        '''</summary>
        Friend Shared ReadOnly Property PFP70141() As String
            Get
                Return ResourceManager.GetString("PFP70141", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to M/C CODE CONTROL.
        '''</summary>
        Friend Shared ReadOnly Property PFP70155() As String
            Get
                Return ResourceManager.GetString("PFP70155", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DYEING METHOD CONTROL.
        '''</summary>
        Friend Shared ReadOnly Property PFP70156() As String
            Get
                Return ResourceManager.GetString("PFP70156", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DYESTUFFS PRESCRIPTION CODE CONTROL.
        '''</summary>
        Friend Shared ReadOnly Property PFP70231() As String
            Get
                Return ResourceManager.GetString("PFP70231", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BASIC CODE CONTROL.
        '''</summary>
        Friend Shared ReadOnly Property PFP71710T() As String
            Get
                Return ResourceManager.GetString("PFP71710T", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HR CODE CONTROL.
        '''</summary>
        Friend Shared ReadOnly Property PFP74411() As String
            Get
                Return ResourceManager.GetString("PFP74411", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HR BASIC CODE CONTROL.
        '''</summary>
        Friend Shared ReadOnly Property PFP74471() As String
            Get
                Return ResourceManager.GetString("PFP74471", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PASSWORD MANAGEMENT.
        '''</summary>
        Friend Shared ReadOnly Property PFP99992() As String
            Get
                Return ResourceManager.GetString("PFP99992", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort.
        '''</summary>
        Friend Shared ReadOnly Property tit_Sort() As String
            Get
                Return ResourceManager.GetString("tit_Sort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use.
        '''</summary>
        Friend Shared ReadOnly Property tit_Use() As String
            Get
                Return ResourceManager.GetString("tit_Use", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vietnames Language.
        '''</summary>
        Friend Shared ReadOnly Property vietnamese() As String
            Get
                Return ResourceManager.GetString("vietnamese", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
